# Generated by Django 5.2.7 on 2025-11-03 02:24

import django.core.validators
import voleibol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voleibol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, verbose_name='Nombre del Equipo')),
                ('category', models.CharField(choices=[('M', 'Varonil'), ('F', 'Femenil')], max_length=1, verbose_name='Categoría')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[voleibol.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Logo del Equipo (Opcional)')),
                ('payment_proof', models.FileField(upload_to='payments/', validators=[voleibol.models.validate_file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])], verbose_name='Comprobante de Pago')),
                ('payment_reference', models.CharField(max_length=80, verbose_name='Número de Referencia de Pago')),
                ('delegate_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono/Celular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Equipo',
                'verbose_name_plural': 'Registros de Equipos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Voleibol',
        ),
    ]
